### ISSUE TITLE
Docs: unable to find installation information for Debian-based distributions

### ISSUE THREAD

**Issue by JefferMarcelino** [GraHms/Latin-Lang#4]
Description:
I am interested in trying out Samora Lang, and I've been looking for installation instructions to use it on my Debian-based distribution (e.g., Ubuntu). However, I could not find any official package or direct support for Debian-based systems.

Possible Solutions:
1. Provide pre-built binaries or tarballs for Linux distributions, including Debian-based systems.
2. Offer build instructions from source for Debian-based distributions in the official repository.

Note:
As a workaround, I might consider setting up a virtual machine with Arch Linux to follow the current installation instructions, but having native support for Debian-based distributions would be highly appreciated.

Thank you for your attention to this matter.

**Comment by snhane** [comment]
the possible solution 1 is introduced in this PR #24
