### ISSUE TITLE
Incorrect Handling of Standard Output and Standard Error

### ISSUE THREAD

**Issue by JefferMarcelino** [GraHms/Latin-Lang#9]
Hey @GraHms,

Hope you're doing well. I'm currently testing out Samora-lang, and I must say it's been an interesting experience. However, I've encountered a couple of issues that I could use your help with.

Firstly, when using the language on my computer and attempting to print a simple value, like **10**, I noticed that it displays **10null** instead. This seems to happen with any print statement, even when dealing with strings.
![IMG-20230726-WA0008.jpg](https://github.com/GraHms/Samora-Lang/assets/77571208/0970e871-6049-4746-9811-af68d3cab05e)

Secondly, I created a scene in NodeJS to execute the code present in the **tempFilePath** variable, capture the stdout and stderr, and then send it as a response to the user. 
![IMG-20230726-WA0002.jpg](https://github.com/GraHms/Samora-Lang/assets/77571208/efa41f43-f187-4f93-a4da-68a19ee589e2)

Strangely, the stdout and stderr outputs appear to be swapped. 
![IMG-20230726-WA0001.jpg](https://github.com/GraHms/Samora-Lang/assets/77571208/423af7f8-c3d4-440e-acf3-e0e99cc9daa3)

I have a hunch that the second issue might be related to the first one.

Can you help me?

**Comment by GraHms** [comment]
The last merge solved this issue
